### PR TITLE
string.QxEquals operator

### PR DESCRIPTION
**Pull request by djanosik**
Adds support for case and accent sensitive string comparisons.

### CODE REVIEW

**Comment by danielwertheim** [comment]
Thanks! Will take it into the next release. I've written a small contribution guide [https://github.com/danielwertheim/SisoDb-Provider/wiki/Contribute], that hopefully will give the actual changes of the pull request last in the tree, making it easier for me to pick them in.

//Daniel

**Comment by djanosik** [comment]
Ok, thanks. I just wonder why you don't use NuGet package restore. ;)

**Comment by danielwertheim** [comment]
Because I wan't as little effect as possible on my project files and the compiling process. Why should it have to look for missing NuGets every time it compiles? Compiling is slow as it is already.

//Daniel

**Comment by djanosik** [comment]
Ok, it makes sense. But it does not have to look for missing packages on every build. You can configure this in the NuGet.targets file.

**Comment by danielwertheim** [comment]
Replaced with `QxIsExactly` which is supported for Strings only (NOT Texts).

//Daniel

**Pull request closed without merging**
